<a href="https://colab.research.google.com/github/Jsoyoung/mulcamp34/blob/main/numpy_240103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy
- 선형대수, 행렬 수치연산과 관련된 라이브러리

In [ ]:
import numpy as np  # Numpy 라이브러리를 불러오기    # ModuleNotFoundError: No module named '~~' 오류 : ~~ 라이브러리 설치하기!
                                                   # !pip install ~~ : 가상환경 말고 주피터랩 안에서 임시로 설치하는 방법

print(np.__version__)

1.26.3


In [ ]:
num1 = [1,2,3,4]  # 리스트 형식
num2 = [3,4,5,6]

num1 + num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [ ]:
# 데이터를 numpy 배열로 변경

arr1 = np.array(num1)
arr2 = np.array(num2)
arr1

array([1, 2, 3, 4])

In [ ]:
arr2

array([3, 4, 5, 6])

In [ ]:
arr1 + arr2

array([ 4,  6,  8, 10])

In [ ]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [ ]:
a1.dtype   # 데이터 타입 확인
           # Python : int    # Numpy : int8, int16, int32, int64

dtype('int32')

In [ ]:
np.array([0.5, 2, 0.01, 8]).dtype

dtype('float64')

## Numpy 배열 생성
- 1차원, 2차원, 3차원... 배열 생성

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.arange(12).reshape(4,5)  # 4*5 배열에 들어갈 원소 개수가 부족하면 에러 발생

ValueError: cannot reshape array of size 12 into shape (4,5)

In [ ]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
b1 = np.arange(12).reshape(4,3)
b1.shape  # 출력값 튜플

(4, 3)

In [ ]:
b2 = np.arange(5)
b2.shape  # 1차원 배열 표시 방법 : (n,)

(5,)

In [ ]:
# 범위의 시작과 끝 정하기 배열 생성
np.linspace(0,10,5)  # 0과 10 사이에 숫자가 5개 있도록 만들어달라

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## Numpy 기초 문법 배우는 이유
- 문과생 : 데이터 분석가, 기초문법 있구나! 하고 넘어가면 끝
- 이공계 : 수치연산, 배열, 수식 활용해서 문제 풀이
          + 클래스, 딥러닝 클래스, NumPy를 활용해서 딥러닝 알고리즘 적용하여 클래스 & 라이브러리
          + 밑바닥부터 시작하는 딥러닝3

In [ ]:
# 단위행렬
arr_I = np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr_I.shape

(3, 3)

In [ ]:
np.array(['1.5', '0.62'])  # 데이터 형변환

array(['1.5', '0.62'], dtype='<U4')

In [ ]:
# astype()  # pandas에서 사용 가능
arr = np.array(['1.5', '0.62'])
num_arr = arr.astype(float)  # astype을 통해 숫자 형태로 변경  # float: 실수
num_arr.dtype

dtype('float64')

In [ ]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(int)  # int는 실수와 같이 쓸 때는 별로,, 값이 유실됨  # 일치시키고 싶으면 float 형태로 변환하는 게 좋음
num_f1

array([10, 21,  0,  4,  5])

In [ ]:
# p.224
# 난수 : 무작위로 숫자를 추출한다

np.random.rand(2, 3)  # rand: 0~1 사이의 실수 난수를 가짐. 괄호 안은 배열

array([[0.86285307, 0.35853185, 0.29890949],
       [0.49654064, 0.92957784, 0.18903782]])

In [ ]:
np.random.randint(1, 100, 10)  # randint: 범위 지정 후 그 사이의 난수

array([39, 59, 21, 13, 34, 72, 91, 32, 15, 12])

In [ ]:
# 로또 번호 생성기

In [ ]:
np.random.randint(1, 45, 6)

array([21,  4, 12, 36,  5, 11])

In [ ]:
import random

def generate_lotto_numbers():
    lotto_numbers = []

    while len(lotto_numbers) < 6:
        number = random.randint(1, 45)
        if number not in lotto_numbers:
            lotto_numbers.append(number)

    return sorted(lotto_numbers)

if __name__ == "__main__":
    lotto_numbers = generate_lotto_numbers()
    print("로또 번호: ", lotto_numbers)


로또 번호:  [1, 11, 17, 28, 32, 33]


In [ ]:
import random

def generate_lotto_numbers():
    lotto_numbers = [random.randint(1, 45) for _ in range(6)]
    lotto_numbers.sort()
    return lotto_numbers

if __name__ == "__main__":
    lotto_result = generate_lotto_numbers()
    print("로또 번호: {}".format(lotto_result))

로또 번호: [27, 27, 28, 29, 30, 36]


In [ ]:
import random

def generate_lotto_numbers():  # 로또번호 생성 함수
    lotto_numbers = set()   # 중복된 요소 제거

    while len(lotto_numbers) < 6:
        number = random.randint(1, 45)
        lotto_numbers.add(number)

    return sorted(lotto_numbers)  # 시퀀스 오름차순 정렬

# 로또 번호 생성
lotto_numbers = generate_lotto_numbers()
print("생성된 로또 번호:", lotto_numbers)

생성된 로또 번호: [9, 13, 23, 33, 35, 36]


## 배열의 연산
p.225

In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


## 비교연산

In [ ]:
arr1 > 20

array([False, False,  True,  True])

## 통계 연산
- Numpy, 합, 평균, 표준 편차, 분산, 최솟값, 최댓값, 누적합, 누적 곱 메서드가 존재한다.
    + 기술통계량 (Descriptive Statistics) : 현재 데이터 상태를 표현(=묘사, Describe) 한다.

- 통계 : 평균이 전부다! (Mean is Everything)
    + 모수 통계
    + 비모수 통계
    + 베이지안 통계
      

In [ ]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [ ]:
arr3.sum()

10

In [ ]:
arr3.mean()

2.0

In [ ]:
arr3.std() # 표준편차

1.4142135623730951

In [ ]:
arr3.var() # 분산

2.0

## 누적합과 누적곱
- cumsum() : 누적합
- cumprod() : 누적곱

In [ ]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [ ]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [ ]:
arr4.cumprod()

array([ 1,  2,  6, 24])

## 행렬연산
- 선형 대수(Linear Algebra)를 위한 2차원 배열 연산도 지원
- p229, 행렬곱, 전치행렬, 역행렬, 행렬식 사용 예시

In [ ]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [ ]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

In [ ]:
A.dot(B)  # 행렬 곱

array([[0, 1],
       [6, 7]])

In [ ]:
A.transpose()  # 전치 행렬

array([[0, 2],
       [1, 3]])

In [ ]:
np.linalg.inv(A)  # 역행렬

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

## 배열의 인덱싱과 슬라이싱(p.230)
- string, list, tuple과 동일한 방법으로 접근

In [ ]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
a1[3]

30

In [ ]:
# 50을 70으로 변경하고 싶음
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [ ]:
# 리스트 통해서 추출
a1[[0, 2, 4]]  # 인덱스 위치 -> 리스트화

array([ 0, 20, 40])

In [ ]:
idx_list = [0, 2, 4]
a1[idx_list]  # 위의 경우보다 이렇게 하는 것이 더 일반적

array([ 0, 20, 40])

In [ ]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2  # 첫번째 열, 첫번째 행 0부터 시작

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
a2[0,1]

20

In [ ]:
# 90을 95로 변경
a2[2, 2] = 95     # pandas 가공할 때도 유사하게 사용됨
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[1,0] = 41
a2

array([[10, 20, 30],
       [41, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[0] = [1, 2, 3]  # 좋지 못한 코드
a2

array([[ 1,  2,  3],
       [41, 50, 60],
       [70, 80, 95]])

In [ ]:
# 정석
a2[0] = np.array([4,5,6])  # a2[0]이 배열이므로 형식을 배열(array)로 맞춰주는 것
a2

array([[ 4,  5,  6],
       [41, 50, 60],
       [70, 80, 95]])

- 2차원 배열의 행과 열 위치 지정해서 원소 추출
    + (행의 위치1, 열의 위치1 / 행의 위치2, 열의 위치2)

In [ ]:
a2

array([[ 4,  5,  6],
       [41, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[[0, 2], [0, 1]]  # ([첫번째 행, 두번째 행], [첫번째 열, 두번째 열])

array([ 4, 80])

In [ ]:
a2[0, 0] , a2[2, 1]  # 위 코드 값의 의미

(4, 80)

In [ ]:
a2[0, 2], a2[0, 1]

(6, 5)

## 배열 조건문
- pandas 문법과 유사하다

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
[a>3]

[array([False, False, False,  True,  True,  True])]

In [ ]:
a[a>3]

array([4, 5, 6])

In [ ]:
a % 2 == 0  # 실무에서는 이런 코드를 작성하는 것이 핵심 !!!

array([False,  True, False,  True, False,  True])

## 배열의 슬라이싱(p.234)

In [ ]:
b1 = np.array([0, 1, 2, 3, 4, 5])
b1[1:4]

array([1, 2, 3])

In [ ]:
b1[:3]

array([0, 1, 2])

In [ ]:
b1[2:]

array([2, 3, 4, 5])

In [ ]:
b1[0:4:2]

array([0, 2])

In [ ]:
b1[2:5] = np.array([25, 35, 45])  # 시작위치2 부터 끝위치 4(5-1)까지 원소값 변경
b1

array([ 0,  1, 25, 35, 45,  5])

In [ ]:
b1[3:6] = 60
b1

array([ 0,  1, 25, 60, 60, 60])

In [ ]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
b2[1:3, 1:3]  #[행 시작위치:행 끝위치(3-1) : 열 시작위치: 열 끝위치(3-1)]

array([[50, 60],
       [80, 90]])

In [ ]:
b2[1:, 1:]

array([[50, 60],
       [80, 90]])

In [ ]:
nums = [1, 2, 3, ['a', 'b']]
nums[3][0]

'a'

In [ ]:
b2[1][1:3]  # [행][열 슬라이싱]

array([50, 60])

## NumPy 조건문
- np.where : 단일 조건문
- np.select : 다중 조건문

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 0, 1, 2, 3, 4, 50, 60, 70, 80, 90
np.where(arr < 5, arr, arr * 10)  # 조건문이 하나일 때는 이렇게

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 100, 101, 2, 3, 4, 5, 12, 14, 16, 18
# 2 미만일 때는 100을 더해라
# 5 초과일 때는 곱하기 2를 해줘라

# 조건식과 대응되는 결과를 리스트로 만들기
cond_list = [arr > 5, arr < 2]
choice_list = [arr * 2, arr + 100]

np.select(cond_list, choice_list, default = arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

## NumPy 수치연산 (가장 기초적인) 라이브러리
- 문과생, 비전공자 : NumPy의 수치연산 개념이 pandas, scipy, scikit-learn, tensorflow, pytorch 영향을 주었다.
- 이공계 : 수치연산 알고리즘 구현하는 것을 기대, 각 연산의 종류 선형대수, 주요 메서드들에 좀 더 깊은 공부를 해야 함